"""empty message

Revision ID: 1796c04307b1
Revises: 1b99fc0f63a8
Create Date: 2015-06-23 17:10:07.815606

"""

# revision identifiers, used by Alembic.
revision = '1796c04307b1'
down_revision = '1b99fc0f63a8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_assurance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assurance', sa.String(), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_assurance')
    ### end Alembic commands ###
