"""empty message

Revision ID: 1b3a0f954d44
Revises: None
Create Date: 2015-04-14 09:27:46.221018

"""

# revision identifiers, used by Alembic.
revision = '1b3a0f954d44'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
