"""empty message

Revision ID: 261191da479f
Revises: 53450916c7dd
Create Date: 2016-03-08 20:28:59.559774

"""

# revision identifiers, used by Alembic.
revision = '261191da479f'
down_revision = '53450916c7dd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_map', sa.Column('can_email', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_map', 'can_email')
    ### end Alembic commands ###
