"""empty message

Revision ID: 28e16ecacbeb
Revises: 47d6ad6c5892
Create Date: 2015-04-15 10:52:14.107189

"""

# revision identifiers, used by Alembic.
revision = '28e16ecacbeb'
down_revision = '47d6ad6c5892'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('redirect_uri', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'redirect_uri')
    ### end Alembic commands ###
