"""empty message

Revision ID: 3252e7ec3b8c
Revises: 22f51775a6ac
Create Date: 2015-06-23 17:50:19.768153

"""

# revision identifiers, used by Alembic.
revision = '3252e7ec3b8c'
down_revision = '22f51775a6ac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.Column('userid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_assurance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assurance', sa.String(), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_assurance')
    op.drop_table('app_map')
    ### end Alembic commands ###
