"""empty message

Revision ID: 36999c7e0386
Revises: 1b3a0f954d44
Create Date: 2015-04-14 09:30:41.022355

"""

# revision identifiers, used by Alembic.
revision = '36999c7e0386'
down_revision = '1b3a0f954d44'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application')
    ### end Alembic commands ###
