"""empty message

Revision ID: 47d6ad6c5892
Revises: None
Create Date: 2015-04-15 06:22:45.276705

"""

# revision identifiers, used by Alembic.
revision = '47d6ad6c5892'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('secret', sa.String(length=14), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application')
    ### end Alembic commands ###
