"""empty message

Revision ID: 4acb9ccbdfa1
Revises: None
Create Date: 2015-04-14 19:01:09.480061

"""

# revision identifiers, used by Alembic.
revision = '4acb9ccbdfa1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.String(length=14), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('secret', sa.String(length=14), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application')
    ### end Alembic commands ###
