"""empty message

Revision ID: 4cdab7f354d2
Revises: None
Create Date: 2015-04-29 17:49:12.498181

"""

# revision identifiers, used by Alembic.
revision = '4cdab7f354d2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('key_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('access_key', sa.String(), nullable=True),
    sa.Column('refresh_key', sa.String(), nullable=True),
    sa.Column('authorization_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('authenticated', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('secret', sa.String(length=14), nullable=True),
    sa.Column('redirect_uri', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('credentialType', sa.String(), nullable=True),
    sa.Column('identifier', sa.String(), nullable=True),
    sa.Column('secret', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tokeninfo_by_access_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tokeninfo_id', sa.Integer(), nullable=True),
    sa.Column('access_key', sa.String(), nullable=True),
    sa.Column('expire_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tokeninfo_id'], ['key_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_key')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokeninfo_by_access_key')
    op.drop_table('credential')
    op.drop_table('application')
    op.drop_table('user')
    op.drop_table('key_data')
    ### end Alembic commands ###
