"""empty message

Revision ID: 4f4e6f392520
Revises: 28e16ecacbeb
Create Date: 2015-04-18 19:03:49.116219

"""

# revision identifiers, used by Alembic.
revision = '4f4e6f392520'
down_revision = '28e16ecacbeb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokeninfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('refresh_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_key')
    )
    op.create_table('tokeninfo_by_access_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tokeninfo_id', sa.Integer(), nullable=True),
    sa.Column('access_key', sa.String(), nullable=True),
    sa.Column('expire_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tokeninfo_id'], ['tokeninfo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_key')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokeninfo_by_access_key')
    op.drop_table('tokeninfo')
    ### end Alembic commands ###
