"""empty message

Revision ID: 507375f735a2
Revises: 4de95d92a7c3
Create Date: 2015-04-19 20:03:53.325463

"""

# revision identifiers, used by Alembic.
revision = '507375f735a2'
down_revision = '4de95d92a7c3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('key_data', sa.Column('authorization_code', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('key_data', 'authorization_code')
    ### end Alembic commands ###
