"""empty message

Revision ID: 53450916c7dd
Revises: 7d263779502e
Create Date: 2016-03-08 20:08:21.371064

"""

# revision identifiers, used by Alembic.
revision = '53450916c7dd'
down_revision = '7d263779502e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('can_email', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'can_email')
    ### end Alembic commands ###
