"""empty message

Revision ID: 7d263779502e
Revises: 3252e7ec3b8c
Create Date: 2016-01-13 09:15:15.334325

"""

# revision identifiers, used by Alembic.
revision = '7d263779502e'
down_revision = '3252e7ec3b8c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.get_bind().execute("alter table application alter column secret type character varying;")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
