"""empty message

Revision ID: a4910bfd68
Revises: 4cdab7f354d2
Create Date: 2015-04-30 10:06:52.632068

"""

# revision identifiers, used by Alembic.
revision = 'a4910bfd68'
down_revision = '4cdab7f354d2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hash', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'hash')
    ### end Alembic commands ###
