#!/bin/bash
set -e
branch=${TRAVIS_BRANCH}
commit=${TRAVIS_COMMIT}
echo working on $branch/$commit

cd doc
mkdir -p $branch
mv html/* $branch
git config user.email "mag@magwas.rulez.org"
git config user.name "travis on behalf of mag"
git add $branch
git commit -m "$commit"
echo ${GH_TOKEN}|md5sum
git_uri="https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git"
echo ${git_uri}
git push  "${git_uri}" gh-pages
