#!/bin/bash
branch=$(git rev-parse --abbrev-ref HEAD)
commit=$(git rev-parse HEAD)
echo working on $branch/$commit

cd doc
mv html $branch
git config user.email "mag@magwas.rulez.org"
git config user.name "travis on behalf of mag"
git add $branch
git commit -m "$commit"
git push origin gh-pages
