#!/bin/bash
cd /PDOauth
ulimit -c unlimited
export DISPLAY=:0
Xvnc -SecurityTypes=None :0&
export  NSS_DEFAULT_DB_TYPE="sql"
export  I_DONT_MIND_IF_MY_CHROME_PKI_DATABASE_GETS_DELETED=true
export PATH=/firefox:/chromedriver:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
service postgresql start; ret=1 ; while [ $ret != 0 ] ; do psql -c "select count(*) from pg_user;" ; ret=$?; done
./tools/setupdoc
cp /etc/hosts /tmp
echo "127.0.0.1 local.sso.edemokraciagep.org" >>/tmp/hosts
cp /tmp/hosts /etc/hosts
#export DISPLAY=:99.0
#/sbin/start-stop-daemon --start --quiet --pidfile /tmp/cucumber_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1024x768x24
make realclean
make install
make testsetup
make runanchor
make runserver
make runemail
make firefoxtest
/bin/bash -i
