#!/bin/bash
set -xe
chown postgres /var/run/postgresql/
apt update
#apt -y --allow-downgrades install chromium-chromedriver=49.0.2623.108-0ubuntu1.1233 chromium-browser=49.0.2623.108-0ubuntu1.1233 chromium-codecs-ffmpeg=49.0.2623.108-0ubuntu1.1233
apt -y remove nodejs-legacy npm
curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -
apt-get install -y nodejs
npm install -g rollup
npm install jsdom qunit-cli
pip install j2cli
locale-gen en_US.UTF-8

export DISPLAY=:0
export LC_ALL=en_US.UTF-8
Xvnc -SecurityTypes=None :0&
export  NSS_DEFAULT_DB_TYPE="sql"
export  I_DONT_MIND_IF_MY_CHROME_PKI_DATABASE_GETS_DELETED=true
export PATH=/firefox:/chromedriver:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
set +e
service postgresql start; ret=1 ; while [ $ret != 0 ] ; do psql -c "select count(*) from pg_user;" ; ret=$?; done
set -e
./tools/setupdoc
cp /etc/hosts /tmp
echo "127.0.0.1 local.sso.edemokraciagep.org" >>/tmp/hosts
cp /tmp/hosts /etc/hosts
cp src/end2endtest/syslog-ng.conf /etc/syslog-ng/
service syslog-ng restart
cat /dev/xconsole&
set +e
