#!/bin/bash
echo ${GH_TOKEN}|md5sum
#git clone -b gh-pages $(git config remote.origin.url|sed 's/:/\//;s/git@/https:\/\//') doc
git clone -b gh-pages $(git config remote.origin.url) doc
branch=$(git rev-parse --abbrev-ref HEAD)
commit=$(git rev-parse HEAD)
echo working on $branch/$commit
mkdir -p doc/$branch
